(()=>{const start=new Date('2026-08-30T00:00:00-04:00'),end=new Date('2026-09-13T23:59:59-04:00'),today=new Date();const days={
'2026-08-30':['Travel Day','Tampa → Los Angeles → Shanghai · China begins now ✈️','travel'],
'2026-08-31':['Shanghai','Arrive PVG 4:05 PM → Pullman Jing An → easy first evening','shanghai'],
'2026-09-01':['Shanghai','Yuyuan → Oriental Pearl → Nanjing Road → Bund → FLAIR sunset → INS','shanghai'],
'2026-09-02':['Zhangjiajie','Fly to Zhangjiajie → 72 Strange Buildings → optional dancing','zhangjiajie'],
'2026-09-03':['Zhangjiajie','National Forest Park → Yuanjiajie → Bailong → Wowza sunset','zhangjiajie'],
'2026-09-04':['Furong','Tianmen + Glass Bridge → Furong waterfall after dark','furong'],
'2026-09-05':['Chengdu','Furong morning → Business Class HSR → hotpot → rooftop → dancing','chengdu'],
'2026-09-06':['Chengdu','Pandas → Jinli → People’s Park tea → skyline drinks','chengdu'],
'2026-09-07':['Xi’an','Business Class HSR → Muslim Quarter → Great Tang lights','xian'],
'2026-09-08':['Xi’an','Terracotta Warriors → City Wall → Siren rooftop → Psyche','xian'],
'2026-09-09':['Xi’an','Mount Huashan full-day adventure','xian'],
'2026-09-10':['Beijing','Business Class HSR → free afternoon → MO Bar sunset','beijing'],
'2026-09-11':['Beijing','Tiananmen → Forbidden City → Summer Palace → Friday club night','beijing'],
'2026-09-12':['Beijing → Shanghai','Mutianyu Great Wall → Temple of Heaven → fly Shanghai','beijing'],
'2026-09-13':['Shanghai → Home','PVG 10:15 AM → Detroit → Tampa','travel']};
const pad=n=>String(n).padStart(2,'0'),key=`${today.getFullYear()}-${pad(today.getMonth()+1)}-${pad(today.getDate())}`,d=days[key],kicker=document.querySelector('#todayKicker'),title=document.querySelector('#todayTitle'),text=document.querySelector('#todayText'),link=document.querySelector('#todayLink'),progress=document.querySelector('#tripProgress');if(d){kicker.textContent='LIVE TRIP · TODAY';title.textContent=d[0];text.textContent=d[1];link.href='#'+d[2];link.textContent='Open today’s details ↓';document.getElementById(d[2])?.setAttribute('open','');document.querySelectorAll('.route a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+d[2]));const pct=Math.min(100,Math.max(0,((today-start)/(end-start))*100));progress.style.width=pct+'%'}else if(today<start){const diff=Math.ceil((start-today)/86400000);kicker.textContent='TRIP COUNTDOWN';title.textContent=diff+' days to China 🇨🇳';text.textContent='Your pocket command center is ready. Flights, trains, hotels, tours, nightlife, photos and support are all in one place.';progress.style.width='0%'}else{kicker.textContent='CHINA 2026';title.textContent='What a trip. 🇨🇳';text.textContent='The dashboard remains your trip archive, photo guide and shared memory hub.';progress.style.width='100%'}
const unregister=()=>{if('serviceWorker'in navigator)navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister()));if('caches'in window)caches.keys().then(ks=>ks.forEach(k=>caches.delete(k)))};unregister();
const cleanName=s=>s.replace(/·/g,' ').replace(/THE ROOFTOP/gi,'').replace(/FLAIR/gi,'Ritz-Carlton Pudong').replace(/Siren rooftop/gi,'Xi’an City Wall').trim();
const cityName=spot=>spot.closest('.insta-city')?.querySelector('h4')?.textContent?.trim()||'China';
async function resolvePhoto(spot){const name=spot.querySelector('b')?.textContent?.trim();const thumb=spot.querySelector('.spot-thumb');if(!name||!thumb)return;const city=cityName(spot);const q=encodeURIComponent(`${cleanName(name)} ${city} China`);const url=`https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${q}&gsrlimit=5&prop=pageimages&piprop=thumbnail&pithumbsize=420&format=json&origin=*`;try{const r=await fetch(url);const j=await r.json();const pages=Object.values(j.query?.pages||{});const page=pages.find(p=>p.thumbnail?.source)||pages[0];if(page?.thumbnail?.source){thumb.style.backgroundImage=`url('${page.thumbnail.source}')`;thumb.dataset.resolved='true'}}catch(e){}
if(!spot.querySelector('.spot-actions')){const details=spot.querySelector('div:last-child');if(details){const actions=document.createElement('div');actions.className='spot-actions';const mapQ=encodeURIComponent(`${name}, ${city}, China`);actions.innerHTML=`<a class="spot-map" target="_blank" rel="noopener" href="https://maps.apple.com/?q=${mapQ}">📍 Take me there</a><a class="spot-photo-search" target="_blank" rel="noopener" href="https://www.google.com/search?tbm=isch&q=${mapQ}">📷 More photos</a>`;details.appendChild(actions)}}}
function upgradeInstagram(){if(!document.querySelector('.insta-spot'))return;const style=document.createElement('style');style.textContent='.spot-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.spot-map,.spot-photo-search{display:inline-flex;text-decoration:none;padding:5px 8px;border-radius:999px;font-size:8px;font-weight:950;letter-spacing:.04em}.spot-map{background:linear-gradient(135deg,#2563eb,#7c3aed);color:#fff}.spot-photo-search{background:#ffffff0a;border:1px solid #ffffff14;color:#c4b5fd}.spot-thumb{position:relative;overflow:hidden}.spot-thumb:after{content:"";position:absolute;inset:0;background:linear-gradient(180deg,transparent 58%,rgba(0,0,0,.24));pointer-events:none}';document.head.appendChild(style);document.querySelectorAll('.insta-spot').forEach(resolvePhoto)}
const hotels={
 shanghai:{name:'Pullman Shanghai Jing’an',brand:'ALL · Accor',map:'Pullman Shanghai Jing An',amenities:[['🏊','Pool'],['🏋️','24h Gym'],['🧖','Spa'],['♨️','Steam rooms'],['🍽️','Restaurant'],['🍸','Bar'],['🚇','Metro 50m']],note:'Downtown Jing’an; the same property is used again for the final Shanghai night.'},
 zhangjiajie:{name:'Pullman Zhangjiajie',brand:'ALL · Accor',map:'Pullman Zhangjiajie Wulingyuan',amenities:[['🏊','Outdoor pool'],['🏋️','Fitness'],['🍽️','3 restaurants'],['🍸','Lobby bar'],['🥐','Breakfast'],['🅿️','Parking'],['🌿','Garden pool']],note:'Wulingyuan location with easy access to the National Forest Park.'},
 chengdu:{name:'Crowne Plaza Chengdu City Center',brand:'IHG',map:'Crowne Plaza Chengdu City Center',amenities:[['🏊','Indoor heated pool'],['🏋️','Fitness'],['🧖','Spa'],['🍽️','Restaurant'],['🛜','Wi‑Fi'],['🚇','Metro walk'],['🚌','Panda shuttle']],note:'Central CBD location near Taikoo Li / IFS; complimentary Panda Base shuttle advertised from June 23, 2026.'},
 xian:{name:'Wyndham Grand Xi’an South',brand:'Wyndham Grand',map:'Wyndham Grand Xian South',amenities:[['🏊','Indoor pool*'],['🏋️','Gym*'],['🧖','Spa'],['♨️','Hot tub'],['🍽️','Restaurant'],['🍸','Bar'],['🧺','Laundry']],note:'Right by Great Tang All Day Mall. *Recent listings conflict on pool/gym operating status, so verify at check-in.'},
 beijing:{name:'Shangri-La Beijing',brand:'Shangri-La',map:'Shangri-La Beijing Zizhuyuan Road',amenities:[['🏊','25m indoor pool'],['🏋️','Fitness'],['🧖','CHI Spa'],['♨️','Whirlpool'],['🧘','Yoga / Pilates'],['☀️','Sun deck']],note:'Health Club includes the indoor pool, whirlpool, fitness facilities and classes.'}
};
function addHotelAmenities(){if(document.getElementById('hotelAmenityStyles'))return;const st=document.createElement('style');st.id='hotelAmenityStyles';st.textContent='.hotel-amenity-card{background:linear-gradient(145deg,#0f2137,#132a45);border:1px solid rgba(96,165,250,.2);border-radius:18px;padding:13px;margin:9px 0 14px;box-shadow:0 12px 28px rgba(0,0,0,.16)}.hotel-top{display:flex;gap:10px;align-items:flex-start}.hotel-badge{width:40px;height:40px;border-radius:13px;background:linear-gradient(135deg,#2563eb,#14b8a6);display:grid;place-items:center;font-size:20px;box-shadow:0 0 18px rgba(37,99,235,.25)}.hotel-copy{flex:1}.hotel-copy b{display:block;font-size:15px}.hotel-copy small{display:block;color:#8fb7dc;margin-top:2px;font-size:10px}.amenity-strip{display:flex;gap:7px;overflow-x:auto;padding:11px 0 3px;scrollbar-width:none}.amenity-strip::-webkit-scrollbar{display:none}.amenity-chip{flex:0 0 auto;min-width:76px;text-align:center;padding:8px 7px;border-radius:13px;background:rgba(255,255,255,.055);border:1px solid rgba(255,255,255,.08)}.amenity-chip span{display:block;font-size:20px}.amenity-chip small{display:block;margin-top:3px;font-size:8px;color:#d3dfec;font-weight:850}.hotel-note{font-size:9px;color:#94a8bd;margin-top:8px}.hotel-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.hotel-actions a{display:inline-flex;text-decoration:none;padding:6px 9px;border-radius:999px;background:#ffffff0a;border:1px solid #ffffff12;font-size:9px;font-weight:900;color:#bfdbfe}';document.head.appendChild(st);Object.entries(hotels).forEach(([id,h])=>{const city=document.getElementById(id),body=city?.querySelector('.city-body');if(!body||body.querySelector('.hotel-amenity-card'))return;let heading=[...body.querySelectorAll('h3')].find(x=>/Hotel/i.test(x.textContent));if(!heading){heading=document.createElement('h3');heading.textContent='Hotel + amenities';const tonight=[...body.querySelectorAll('h3')].find(x=>x.textContent.trim()==='Tonight');if(tonight)body.insertBefore(heading,tonight);else body.appendChild(heading)}const existing=heading.nextElementSibling?.classList.contains('info-card')?heading.nextElementSibling:null;const card=document.createElement('div');card.className='hotel-amenity-card';card.innerHTML=`<div class="hotel-top"><div class="hotel-badge">🏨</div><div class="hotel-copy"><b>${h.name}</b><small>${h.brand} · reservation locked</small></div></div><div class="amenity-strip">${h.amenities.map(a=>`<div class="amenity-chip"><span>${a[0]}</span><small>${a[1]}</small></div>`).join('')}</div><div class="hotel-note">${h.note}</div><div class="hotel-actions"><a target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(h.map)}">📍 Map</a><a target="_blank" rel="noopener" href="https://www.google.com/search?q=${encodeURIComponent(h.name+' official hotel')}">🌐 Hotel site</a></div>`;if(existing)existing.insertAdjacentElement('afterend',card);else heading.insertAdjacentElement('afterend',card)})}
window.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.closest('.club-photos')?.classList.add('image-error')}));upgradeInstagram();addHotelAmenities()});})();