(()=>{
const TIKTOK='https://www.tiktok.com/t/ZP8v1DS5Q/';
const MAP_QUERY='浅深 成都店 天府一街798号';
function styles(){if(document.getElementById('chengduSpaStyles'))return;const style=document.createElement('style');style.id='chengduSpaStyles';style.textContent=`
.chengdu-spa{margin:14px 0 18px;padding:14px;border-radius:20px;background:radial-gradient(circle at 88% 0,rgba(45,212,191,.2),transparent 36%),linear-gradient(145deg,#10252d,#111a2a);border:1px solid rgba(94,234,212,.25);box-shadow:0 16px 38px rgba(0,0,0,.2)}
.chengdu-spa-head{display:flex;gap:11px;align-items:center}.chengdu-spa-icon{width:46px;height:46px;flex:0 0 46px;border-radius:15px;display:grid;place-items:center;font-size:24px;background:linear-gradient(135deg,#14b8a6,#0ea5e9);box-shadow:0 9px 22px rgba(14,165,233,.24)}
.chengdu-spa-kicker{font-size:8px;font-weight:950;letter-spacing:.14em;color:#5eead4}.chengdu-spa h4{font-size:18px;line-height:1.08;margin:3px 0;color:#fff}.chengdu-spa-cn{font-size:9px;color:#9fb8c8;margin-top:3px}
.chengdu-spa-badges{display:flex;gap:6px;flex-wrap:wrap;margin:11px 0}.chengdu-spa-badge{padding:5px 8px;border-radius:999px;background:rgba(20,184,166,.12);border:1px solid rgba(94,234,212,.18);color:#99f6e4;font-size:7px;font-weight:950;letter-spacing:.05em}
.chengdu-spa-copy{font-size:10px;line-height:1.5;color:#c0d0de;margin:0 0 10px}.chengdu-spa-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.chengdu-spa-fact{padding:10px;border-radius:14px;background:#ffffff07;border:1px solid #ffffff0e}.chengdu-spa-fact b{display:block;font-size:8px;color:#67e8f9;text-transform:uppercase;letter-spacing:.07em;margin-bottom:4px}.chengdu-spa-fact span{display:block;font-size:9px;line-height:1.45;color:#d3dfeb}
.chengdu-spa-address{margin-top:9px;padding:10px;border-radius:14px;background:rgba(14,165,233,.08);border:1px solid rgba(56,189,248,.14);font-size:9px;line-height:1.45;color:#bae6fd}.chengdu-spa-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.chengdu-spa-actions a{display:inline-flex;align-items:center;text-decoration:none;padding:7px 10px;border-radius:999px;background:#ffffff0b;border:1px solid #ffffff15;color:#ccfbf1;font-size:8px;font-weight:900}.chengdu-spa-note{font-size:8px;line-height:1.45;color:#8296aa;margin:9px 1px 0}
@media(max-width:380px){.chengdu-spa-grid{grid-template-columns:1fr}}
`;document.head.appendChild(style)}
function init(){const body=document.querySelector('#chengdu .city-body');if(!body||body.querySelector('.chengdu-spa'))return;styles();const card=document.createElement('section');card.className='chengdu-spa';card.setAttribute('aria-label','Qianshen Cheersum Spa details');card.innerHTML=`<div class="chengdu-spa-head"><div class="chengdu-spa-icon">♨️</div><div><div class="chengdu-spa-kicker">CHENGDU · SAVED EXPERIENCE</div><h4>Qianshen / Cheersum Spa</h4><div class="chengdu-spa-cn">浅深（成都店）</div></div></div><div class="chengdu-spa-badges"><span class="chengdu-spa-badge">OPEN 24 HOURS</span><span class="chengdu-spa-badge">5 FLOORS</span><span class="chengdu-spa-badge">POOLS + SAUNAS</span></div><p class="chengdu-spa-copy">The viral all-day spa experience from your TikTok: soak, eat, relax, play and rest in one large wellness complex.</p><div class="chengdu-spa-grid"><div class="chengdu-spa-fact"><b>Water & wellness</b><span>Multiple heated pools, cold plunge, swimming pool, dry sauna and thermal rooms.</span></div><div class="chengdu-spa-fact"><b>Relax & play</b><span>Rest and sleep areas, private rooms, cinema, games and a cave-style library.</span></div><div class="chengdu-spa-fact"><b>Food</b><span>Unlimited fruit, drinks and snacks; meal/buffet access depends on the package.</span></div><div class="chengdu-spa-fact"><b>Creator’s price</b><span>About €30 in the shared TikTok. Confirm the current entry and meal package at arrival.</span></div></div><div class="chengdu-spa-address"><b>📍 No. 798 Tianfu 1st Street, Chengdu Hi-tech Zone</b><br>Show a driver: 成都 天府一街798号 浅深度假酒店</div><div class="chengdu-spa-actions"><a target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(MAP_QUERY)}">📍 Apple Maps</a><a target="_blank" rel="noopener" href="https://www.google.com/search?q=${encodeURIComponent(MAP_QUERY)}">🔎 Search venue</a><a target="_blank" rel="noopener" href="${TIKTOK}">▶ Watch TikTok</a></div><p class="chengdu-spa-note">Prices, included meals and room access can vary by package. Verify at check-in before paying.</p>`;const headings=[...body.querySelectorAll(':scope > h3')];const tonight=headings.find(h=>h.textContent.trim().toLowerCase()==='tonight');if(tonight)body.insertBefore(card,tonight);else body.appendChild(card)}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
