(()=>{
const picks={
  shanghai:{name:'INS',note:'High-energy commercial dance-club complex near Fuxing Park. Best all-around dancing choice for Sep 1, even on a Tuesday.',when:'BEST NIGHT · SEP 1'},
  zhangjiajie:{name:'S·π PLUS',note:'The strongest dedicated dance-club option in the current Zhangjiajie research. Go after 72 Strange Buildings if the group still wants a late night.',when:'BEST NIGHT · SEP 2'},
  furong:{name:'No dedicated club recommended',note:'Furong is the one exception: the current trip research says the illuminated waterfall and stilt-house town are far more worthwhile than leaving for a nightclub. If you want music afterward, keep it to a casual local bar near the ancient town.',when:'PHOTO NIGHT · SEP 4'},
  chengdu:{name:'The Butterfly',note:'Featured Saturday dance-club pick after drinks at THE ROOFTOP Niccolo. Monster House and Pose Club remain strong backups.',when:'BEST NIGHT · SEP 5'},
  xian:{name:'Psyche',note:'Featured electronic/dance choice after Siren rooftop and the illuminated City Wall. Check the event lineup that afternoon before committing.',when:'BEST NIGHT · SEP 8'},
  beijing:{name:'Groundless Factory',note:'Warehouse-style electronic dancing in the 798 area. This is the strongest club-style night after the imperial sightseeing day.',when:'BEST NIGHT · SEP 11'}
};
const css=document.createElement('style');css.textContent=`.dance-pick{margin:13px 0;background:linear-gradient(145deg,#312e81,#6d28d9 60%,#9333ea);color:#fff;border-radius:19px;padding:15px;box-shadow:0 12px 26px rgba(76,29,149,.22);position:relative;overflow:hidden}.dance-pick:after{content:'♪';position:absolute;right:14px;top:-14px;font-size:84px;color:rgba(255,255,255,.08);font-weight:900}.dance-pick .dance-label{font-size:9px;font-weight:950;letter-spacing:.15em;color:#ddd6fe}.dance-pick b{display:block;font-size:20px;margin:4px 0 5px}.dance-pick p{color:#ede9fe!important;margin:0!important;font-size:13px}.dance-pick em{display:inline-block;margin-top:9px;font-style:normal;font-size:9px;font-weight:950;letter-spacing:.06em;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.15);padding:5px 8px;border-radius:999px}`;document.head.appendChild(css);
Object.entries(picks).forEach(([id,p])=>{const city=document.getElementById(id);if(!city||city.querySelector('.dance-pick'))return;const inside=city.querySelector('.inside');if(!inside)return;const h3=[...inside.querySelectorAll('h3')].find(x=>x.textContent.trim()==='Tonight');if(!h3)return;const card=document.createElement('div');card.className='dance-pick';card.innerHTML=`<div class="dance-label">💃 DANCE CLUB PICK</div><b>${p.name}</b><p>${p.note}</p><em>${p.when}</em>`;h3.insertAdjacentElement('afterend',card)});
})();