(()=>{
const VERCEL_API='https://china-2026-trip-one.vercel.app/api/restaurants';
const API_ENDPOINT=location.hostname.endsWith('.vercel.app')?'/api/restaurants':VERCEL_API;
const CACHE_TTL=60000;
let activeController=null,lastResult=null,lastLookupAt=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const miles=m=>m==null?'Nearby':m<160?`${Math.round(m)} m`:`${(m/1609.344).toFixed(1)} mi`;
function styles(){if(document.getElementById('hungryStyles'))return;const s=document.createElement('style');s.id='hungryStyles';s.textContent=`
.hungry-fab{position:fixed;right:15px;bottom:92px;z-index:70;border:0;border-radius:999px;padding:12px 16px;background:linear-gradient(135deg,#f97316,#ef4444);color:#fff;font:900 13px/1 system-ui;box-shadow:0 14px 35px rgba(239,68,68,.38);display:flex;align-items:center;gap:7px}.hungry-fab:active{transform:scale(.96)}
.hungry-modal{position:fixed;inset:0;z-index:120;background:rgba(3,8,18,.78);backdrop-filter:blur(15px);display:none;align-items:flex-end;padding-top:calc(env(safe-area-inset-top,0px) + 76px);box-sizing:border-box}.hungry-modal.show{display:flex}.hungry-sheet{width:100%;max-height:calc(100dvh - env(safe-area-inset-top,0px) - 90px);overflow:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;border-radius:28px 28px 0 0;padding:0 15px calc(24px + env(safe-area-inset-bottom,0px));background:radial-gradient(circle at 80% 0,rgba(249,115,22,.18),transparent 30%),linear-gradient(180deg,#111d30,#08111f);border-top:1px solid rgba(255,255,255,.14);box-shadow:0 -25px 80px rgba(0,0,0,.45)}
.hungry-sheet-top{position:sticky;top:0;z-index:4;background:linear-gradient(180deg,#111d30 72%,rgba(17,29,48,.96));padding:14px 0 10px}.hungry-handle{width:42px;height:4px;border-radius:9px;background:#ffffff30;margin:0 auto 12px}.hungry-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.hungry-kicker{font-size:9px;letter-spacing:.15em;font-weight:950;color:#fb923c}.hungry-head h2{font-size:28px;margin:4px 0}.hungry-close{width:42px;height:42px;flex:0 0 42px;border:1px solid #ffffff24;background:#ffffff12;color:#fff;border-radius:50%;font-size:24px;line-height:1;display:grid;place-items:center}.hungry-status{color:#a9b8ca;font-size:11px;margin:3px 0 4px}.hungry-list{display:grid;gap:9px;padding-top:8px}.food-card{display:grid;grid-template-columns:38px 1fr auto;gap:10px;align-items:start;padding:12px;border-radius:17px;background:#ffffff08;border:1px solid #ffffff10}.food-rank{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;background:linear-gradient(135deg,#f97316,#ef4444);font-weight:950}.food-name{font-size:14px;font-weight:900;color:#fff}.food-meta{font-size:10px;color:#a8bbd0;margin-top:4px}.food-price{font-size:12px;font-weight:950;color:#fbbf24}.food-map{display:inline-flex;margin-top:7px;text-decoration:none;padding:6px 9px;border-radius:999px;background:#ffffff0b;border:1px solid #ffffff12;color:#bfdbfe;font-size:9px;font-weight:900}.hungry-action{display:inline-flex;border:0;border-radius:999px;padding:9px 12px;background:linear-gradient(135deg,#f97316,#ef4444);color:#fff;font-weight:900}.hungry-note{padding:13px;border-radius:15px;background:#ffffff07;border:1px solid #ffffff10;color:#b9c7d7;font-size:11px;line-height:1.45}.hungry-note a{color:#fdba74}.hungry-spinner{width:24px;height:24px;border:3px solid #ffffff20;border-top-color:#fb923c;border-radius:50%;animation:hungryspin .8s linear infinite;margin:25px auto}@keyframes hungryspin{to{transform:rotate(360deg)}}`;
document.head.appendChild(s)}
function cleanLegacyNav(){const old=document.getElementById('hungryNav');if(old){const bar=old.parentElement;old.remove();if(bar){bar.style.removeProperty('grid-template-columns')}}}
function renderRestaurants(items,status){const list=document.getElementById('hungryList');document.getElementById('hungryStatus').textContent=status||'Top-rated restaurants near your live location';list.innerHTML=items.map((r,i)=>`<div class="food-card"><div class="food-rank">${i+1}</div><div><div class="food-name">${esc(r.name)}</div><div class="food-meta">⭐ ${Number(r.rating).toFixed(1)} · ${Number(r.reviews).toLocaleString()} reviews · ${esc(r.cuisine)} · ${miles(r.distanceMeters)}</div>${r.address?`<div class="food-meta">${esc(r.address)}</div>`:''}<a class="food-map" target="_blank" rel="noopener" href="${esc(r.maps)}">📍 Open in Maps</a></div><div class="food-price">${esc(r.price)}</div></div>`).join('')||'<div class="hungry-note">No highly rated restaurants were returned nearby. Try again after moving to another area.</div>'}
function fallback(lat,lng,message){const list=document.getElementById('hungryList'),q=encodeURIComponent('restaurants');const google=`https://www.google.com/maps/search/${q}/@${lat},${lng},15z`;const apple=`https://maps.apple.com/?q=restaurants&ll=${lat},${lng}`;document.getElementById('hungryStatus').textContent='Your live GPS location is ready';list.innerHTML=`<div class="hungry-note">📍 <b>Location acquired.</b><br>${esc(message)}<br><br><a class="hungry-action" target="_blank" rel="noopener" href="${apple}">🍎 Apple Maps nearby</a> &nbsp; <a class="hungry-action" target="_blank" rel="noopener" href="${google}">🗺️ Google Maps nearby</a></div>`}
async function fetchRestaurants(lat,lng,accuracy){activeController?.abort();activeController=new AbortController();const status=document.getElementById('hungryStatus');status.textContent=`Location found · accurate to about ${Math.round(accuracy)} m · finding restaurants…`;const r=await fetch(`${API_ENDPOINT}?lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}`,{headers:{Accept:'application/json'},signal:activeController.signal});if(!r.ok)throw new Error(`Restaurant service returned ${r.status}`);const data=await r.json();lastResult=data;lastLookupAt=Date.now();renderRestaurants(data.restaurants,`Top ${data.restaurants.length} nearby · centered on your phone’s live GPS location`)}
async function lookup(force=false){const list=document.getElementById('hungryList'),status=document.getElementById('hungryStatus');if(!force&&lastResult&&Date.now()-lastLookupAt<CACHE_TTL){renderRestaurants(lastResult.restaurants,`Top ${lastResult.restaurants.length} nearby · refreshed less than a minute ago`);return}status.textContent='Finding your precise location…';list.innerHTML='<div class="hungry-spinner"></div>';if(!navigator.geolocation){list.innerHTML='<div class="hungry-note">This browser does not support device location.</div>';return}navigator.geolocation.getCurrentPosition(async pos=>{const {latitude:lat,longitude:lng,accuracy}=pos.coords;try{await fetchRestaurants(lat,lng,accuracy)}catch(e){if(e.name==='AbortError')return;fallback(lat,lng,'Live restaurant ratings are temporarily unavailable.')}} ,()=>{status.textContent='Location permission needed';list.innerHTML='<div class="hungry-note">To find restaurants close to where you are standing, allow Location access for this website in your browser settings, then tap <b>Try again</b>.<br><br><button class="hungry-action" id="hungryRetry">📍 Try again</button></div>';document.getElementById('hungryRetry')?.addEventListener('click',()=>lookup(true))},{enableHighAccuracy:true,timeout:12000,maximumAge:30000})}
function init(){if(document.getElementById('hungryModal'))return;cleanLegacyNav();styles();const btn=document.createElement('button');btn.className='hungry-fab';btn.type='button';btn.setAttribute('aria-label','Find highly rated restaurants near me');btn.innerHTML='🍜 <span>Hungry?</span>';document.body.appendChild(btn);const modal=document.createElement('div');modal.className='hungry-modal';modal.id='hungryModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','hungryTitle');modal.innerHTML='<div class="hungry-sheet"><div class="hungry-sheet-top"><div class="hungry-handle"></div><div class="hungry-head"><div><div class="hungry-kicker">LIVE · NEAR YOU</div><h2 id="hungryTitle">Hungry? 🍜</h2></div><button class="hungry-close" aria-label="Close restaurant finder">×</button></div><div class="hungry-status" id="hungryStatus">Using your phone location to find the best food nearby.</div></div><div class="hungry-list" id="hungryList"></div></div>';document.body.appendChild(modal);const open=()=>{modal.classList.add('show');document.body.style.overflow='hidden';lookup()},close=()=>{modal.classList.remove('show');document.body.style.overflow='';activeController?.abort()};btn.addEventListener('click',open);modal.querySelector('.hungry-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))close()})}
window.ChinaTrip=window.ChinaTrip||{};window.ChinaTrip.hungry={lookup,endpoint:API_ENDPOINT};
window.addEventListener('DOMContentLoaded',init);
})();