(()=>{
const cityImages={
 shanghai:'https://images.unsplash.com/photo-1609153755058-a7cbbf264e9c?auto=format&fit=crop&q=82&w=900',
 zhangjiajie:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Zhangjiajie_at_dawn_1.jpg?width=900',
 furong:'https://epaper.voc.com.cn/hnrb/images/2025-12/11/T20/res03_attpic_brief.jpg',
 chengdu:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Taikoo_Li_Chengdu_%26_Daci_Temple_at_Night.jpg?width=900',
 xian:'https://images.unsplash.com/photo-1780683558609-a27e0bbcb9ee?auto=format&fit=crop&q=82&w=900',
 beijing:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sunset_over_the_Forbidden_City.JPG?width=900'
};
const names=['Shanghai','Zhangjiajie','Furong Ancient Town','Chengdu','Xi’an','Beijing'];
function clean(){const guides=[...document.querySelectorAll('.insta-guide')];guides.slice(1).forEach(g=>g.remove());const guide=guides[0];if(!guide)return false;guide.classList.add('insta-premium');[...guide.querySelectorAll('.insta-city')].forEach((d,i)=>{const key=['shanghai','zhangjiajie','furong','chengdu','xian','beijing'][i];const sum=d.querySelector('summary');if(!sum)return;sum.style.setProperty('--city-photo',`url("${cityImages[key]}")`);const oldPin=sum.querySelector('span');if(oldPin)oldPin.innerHTML='<span class="insta-camera">📸</span>';if(!sum.querySelector('.insta-city-photo')){const ph=document.createElement('div');ph.className='insta-city-photo';ph.style.backgroundImage=`url('${cityImages[key]}')`;sum.prepend(ph)}d.querySelectorAll('.insta-spot').forEach((spot,idx)=>{if(!spot.querySelector('.spot-thumb')){const th=document.createElement('div');th.className='spot-thumb';th.style.backgroundImage=`url('${cityImages[key]}')`;th.style.backgroundPosition=`${20+(idx*13)%70}% ${25+(idx*17)%60}%`;spot.prepend(th)}})});return true}
const st=document.createElement('style');st.id='instagramV2Styles';st.textContent=`
#photos{font-size:15px!important;letter-spacing:.12em!important;color:#111827!important}.insta-premium{display:grid!important;gap:14px!important}.insta-premium .insta-city{background:linear-gradient(145deg,#0b1020,#111827)!important;border:1px solid #2f3a50!important;border-radius:22px!important;overflow:hidden!important;box-shadow:0 18px 42px rgba(15,23,42,.16)!important;color:#fff!important}.insta-premium .insta-city>summary{min-height:108px!important;display:grid!important;grid-template-columns:92px 1fr auto 20px!important;padding:10px!important;gap:12px!important;background:linear-gradient(90deg,rgba(4,8,18,.96),rgba(12,18,34,.88))!important}.insta-city-photo{width:92px;height:88px;border-radius:15px;background-size:cover;background-position:center;box-shadow:inset 0 0 0 1px rgba(255,255,255,.12)}.insta-premium .insta-city>summary>span{display:none!important}.insta-premium .insta-city>summary b{font-size:21px!important;color:#fff!important;text-shadow:0 2px 12px rgba(0,0,0,.45)}.insta-premium .insta-city>summary small{color:#c4b5fd!important;background:#312e81;padding:5px 8px;border-radius:999px}.insta-premium .insta-city>summary i{color:#c4b5fd!important}.insta-premium .insta-list{background:linear-gradient(180deg,#0b1020,#0f172a)!important;border-top:1px solid rgba(255,255,255,.08)!important;padding:9px!important}.insta-premium .insta-spot{display:grid!important;grid-template-columns:82px 32px 1fr!important;gap:10px!important;align-items:center!important;background:rgba(255,255,255,.035)!important;border:1px solid rgba(148,163,184,.11)!important;border-radius:15px!important;margin:8px 0!important;padding:8px!important}.spot-thumb{width:82px;height:72px;border-radius:11px;background-size:cover;background-repeat:no-repeat;box-shadow:inset 0 0 0 1px rgba(255,255,255,.1)}.insta-premium .insta-num{background:linear-gradient(135deg,#ec4899,#7c3aed)!important}.insta-premium .insta-spot b{color:#fff!important;font-size:14px!important}.insta-premium .insta-spot p{color:#aeb8cf!important;font-size:11px!important}.insta-premium .insta-spot em{background:#2e1065!important;color:#e9d5ff!important}.insta-premium .insta-city[open]{box-shadow:0 22px 55px rgba(124,58,237,.16)!important;border-color:#6d28d9!important}@media(max-width:520px){.insta-premium .insta-city>summary{grid-template-columns:76px 1fr auto 16px!important}.insta-city-photo{width:76px;height:72px}.insta-premium .insta-spot{grid-template-columns:68px 28px 1fr!important}.spot-thumb{width:68px;height:62px}}
`;document.head.appendChild(st);
let tries=0;const timer=setInterval(()=>{tries++;if(clean()||tries>12)clearInterval(timer)},250);
})();