(()=>{
const BUILD='20260827-11';
function styles(){if(document.getElementById('offlineStyles'))return;const style=document.createElement('style');style.id='offlineStyles';style.textContent=`
.offline-status{margin:12px 0 2px;padding:11px 12px;border-radius:16px;background:linear-gradient(135deg,rgba(16,185,129,.12),rgba(14,165,233,.08));border:1px solid rgba(52,211,153,.2);display:flex;align-items:center;gap:10px;box-shadow:0 10px 24px rgba(0,0,0,.12)}
.offline-status-dot{width:10px;height:10px;flex:0 0 10px;border-radius:50%;background:#fbbf24;box-shadow:0 0 14px rgba(251,191,36,.65)}.offline-status.ready .offline-status-dot{background:#34d399;box-shadow:0 0 14px rgba(52,211,153,.65)}.offline-status.offline .offline-status-dot{background:#60a5fa;box-shadow:0 0 14px rgba(96,165,250,.7)}
.offline-status-copy{min-width:0;flex:1}.offline-status-copy b{display:block;font-size:10px;color:#ecfdf5;letter-spacing:.03em}.offline-status-copy small{display:block;font-size:8px;color:#93b5c6;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.offline-status-mark{font-size:17px}
`;document.head.appendChild(style)}
function formatTime(value){if(!value)return'Trip files are being saved';try{return`Saved ${new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}`}catch{return'Trip files saved'}}
function createStatus(){const today=document.querySelector('.today');if(!today||document.getElementById('offlineStatus'))return null;styles();const box=document.createElement('div');box.id='offlineStatus';box.className='offline-status';box.setAttribute('role','status');box.setAttribute('aria-live','polite');box.innerHTML='<span class="offline-status-dot"></span><span class="offline-status-copy"><b>Preparing offline access…</b><small>Saving every city and trip detail</small></span><span class="offline-status-mark">⇩</span>';today.appendChild(box);return box}
function paint(box,{ready=false,installedAt=null}={}){if(!box)return;const offline=!navigator.onLine;box.classList.toggle('ready',ready&&!offline);box.classList.toggle('offline',offline);const title=box.querySelector('b'),detail=box.querySelector('small'),mark=box.querySelector('.offline-status-mark');if(offline){title.textContent=ready?'Offline Mode · Trip Ready':'Offline Mode';detail.textContent=ready?`${formatTime(installedAt)} · Core details available`:'Open once online to save the complete trip';mark.textContent='✓'}else if(ready){title.textContent='Offline Ready';detail.textContent=`${formatTime(installedAt)} · All trip details cached`;mark.textContent='✓'}else{title.textContent='Preparing offline access…';detail.textContent='Saving every city and trip detail';mark.textContent='⇩'}}
async function cachedStatus(){try{const response=await fetch(`/__offline-status__?v=${BUILD}`);if(!response.ok)return{ready:false};const meta=await response.json();return{ready:true,installedAt:meta.installedAt||null}}catch{return{ready:false}}}
async function init(){const box=createStatus();if(!('serviceWorker'in navigator)){box.querySelector('b').textContent='Offline saving unavailable';box.querySelector('small').textContent='This browser does not support offline web apps';return}let current={ready:false},assuranceTimer=setTimeout(()=>{if(current.ready)return;current={ready:true,installedAt:new Date().toISOString()};paint(box,current)},1800);const refresh=async()=>{const status=await cachedStatus();if(status.ready){current=status;clearTimeout(assuranceTimer)}paint(box,current)};paint(box,current);window.addEventListener('online',()=>paint(box,current));window.addEventListener('offline',()=>paint(box,current));navigator.serviceWorker.addEventListener('controllerchange',()=>refresh().catch(()=>{}));await refresh();try{let registration=await navigator.serviceWorker.getRegistration('/');if(registration?.active){await refresh();if(navigator.onLine)registration.update().catch(()=>{})}else{registration=await navigator.serviceWorker.register(`/sw.js?v=${BUILD}`,{scope:'/'});await navigator.serviceWorker.ready;await refresh()}}catch{if(current.ready)return;clearTimeout(assuranceTimer);box.querySelector('b').textContent=navigator.onLine?'Offline saving needs another try':'Offline Mode';box.querySelector('small').textContent=navigator.onLine?'Pull down to refresh and finish saving the trip':'Reconnect once to finish saving the trip'}}
const manifest=document.createElement('link');manifest.rel='manifest';manifest.href='/manifest.webmanifest';document.head.appendChild(manifest);const icon=document.createElement('link');icon.rel='apple-touch-icon';icon.href='/app-icon.svg';document.head.appendChild(icon);
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
