(()=>{
const flightData={
 international:[
  {date:'AUG 30–31',title:'Tampa → Los Angeles → Shanghai',airline:'Delta',route:'TPA → LAX → PVG',depart:'Tampa · 7:00 AM · Aug 30',arrive:'Shanghai Pudong · 4:05 PM · Aug 31',class:'International itinerary',transfer:'Private airport pickup included on arrival in Shanghai',status:'CONFIRMED',notes:['Long-haul outbound journey to China','Arrival day is intentionally kept light after the private transfer to Pullman Shanghai Jing An']},
  {date:'SEP 13',title:'Shanghai → Detroit → Tampa',airline:'Delta',route:'PVG → DTW → TPA',depart:'Shanghai Pudong · 10:15 AM',arrive:'Tampa · 4:40 PM scheduled',class:'International itinerary',transfer:'Private airport drop-off included in Shanghai',status:'CONFIRMED',notes:['Final breakfast and hotel checkout before airport transfer','International return routing is Shanghai → Detroit → Tampa']}
 ],
 domestic:[
  {date:'SEP 2',title:'Shanghai → Zhangjiajie',airline:'Shanghai Airlines · FM7225',route:'PVG T1 → DYG T2',depart:'Shanghai Pudong T1 · 10:00 AM',arrive:'Zhangjiajie / Dayong T2 · 12:10 PM',class:'Economy Class',baggage:'20 kg checked per passenger',transfer:'Airport drop-off in Shanghai + private airport pickup in Zhangjiajie included',status:'CONFIRMED',notes:['Driver pickup is coordinated 1–2 hours before departure','Recommended free time after arrival: sunset viewpoint / 72 Strange Buildings']},
  {date:'SEP 12',title:'Beijing → Shanghai',airline:'China Eastern · MU5124',route:'PEK T2 → SHA T2',depart:'Beijing Capital T2 · 7:00 PM',arrive:'Shanghai Hongqiao T2 · 9:20 PM',class:'Economy Class',baggage:'20 kg checked per passenger',transfer:'Airport drop-off in Beijing + private airport pickup in Shanghai included',status:'CONFIRMED',notes:['Touring happens first: Mutianyu Great Wall → Temple of Heaven','Final overnight: Pullman Shanghai Jing An']}
 ]
};
const trainData=[
 {date:'SEP 5',title:'Zhangjiajie West → Chengdu East',number:'G2418',time:'11:50 AM → 4:48 PM',class:'First Class',gate:'2nd Floor',carriage:'Carriage 05',seats:'13A · 13C · 13D · 13F',status:'CONFIRMED',notes:['Private transfer from Furong to Zhangjiajie West and station pickup in Chengdu are included','First Class replaces the originally planned Business Class because Business Class availability is limited']},
 {date:'SEP 7',title:'Chengdu East → Xi’an North',number:'G3880',time:'10:32 AM → 2:21 PM',class:'Business Class',gate:'A13',carriage:'Carriage 08',seats:'01A · 01F · 02A · 02F',status:'CONFIRMED',notes:['Private station drop-off and pickup are included','Recommended free time after arrival: Muslim Quarter street-food tour']},
 {date:'SEP 10',title:'Xi’an North → Beijing West',number:'Train number pending',time:'Estimated 12:04 PM → 4:32 PM',class:'Business Class requested',gate:'Not assigned',carriage:'Not assigned',seats:'Not assigned',status:'NOT YET ON SALE',notes:['Tickets will be sent immediately after successful booking','The operator will try to place the four Business Class seats close together']}
];
const hotelData=[
 {city:'Shanghai',name:'Pullman Shanghai Jing An',dates:'Aug 31 · Sep 1 · Sep 12',rating:'5-Star',address:"No. 330 Meiyuan Road, Jing’an District, Shanghai, 200070, China",map:'Pullman Shanghai Jing An'},
 {city:'Zhangjiajie',name:'Zhangjiajie Jingwu Pullman Hotel',dates:'Sep 2–3',rating:'5-Star',address:'No. 188 Gaoyun Road, Wulingyuan National Scenic Spot District, Zhangjiajie',map:'Zhangjiajie Jingwu Pullman Hotel'},
 {city:'Furong Town',name:'Tea Xitai Holiday Hotel in Furong Town',dates:'Sep 4',rating:'5-Star',address:'Bridge in Furong Town, Henan Village, Hongshilin Town, Guzhang',map:'Tea Xitai Holiday Hotel Furong Town'},
 {city:'Chengdu',name:'Crowne Plaza Chengdu',dates:'Sep 5–6',rating:'5-Star',address:'No. 31 Zongfu Street, Jinjiang District, Chengdu',map:'Crowne Plaza Chengdu 31 Zongfu Street'},
 {city:'Xi’an',name:'Wyndham Grand Xi’an',dates:'Sep 7–9',rating:'5-Star',address:"208 Ci’en East Road, Yanta District, Xi’an",map:'Wyndham Grand Xian 208 Cien East Road'},
 {city:'Beijing',name:'Shangri-La Beijing',dates:'Sep 10–11',rating:'5-Star',address:'No. 29 Zizhuyuan Road, Haidian District, Beijing, 100089, China',map:'Shangri-La Beijing Zizhuyuan Road'}
];
const coverage={included:['Five-star local hotels with breakfast','English-speaking guide on guided touring days','Private seven-seat vehicle throughout the land itinerary','All airport and railway-station pickups and drop-offs','Domestic high-speed rail and economy-class domestic flights','Attraction admission, including listed in-site transport such as cable cars'],excluded:['Lunch and dinner unless explicitly stated','International flights','Visa fees','Personal expenses','Tips and overtime charges']};
function styles(){if(document.getElementById('flightDetailStyles'))return;const s=document.createElement('style');s.id='flightDetailStyles';s.textContent=`
.flight-group>summary{display:flex!important;align-items:center;gap:9px}.flight-group>summary:after{content:'⌄';margin-left:auto;color:#93c5fd;font-size:16px}.flight-group[open]>summary:after{transform:rotate(180deg)}
.flight-detail-wrap{display:grid;gap:9px;padding:10px 0 3px}.flight-card{border-radius:17px;background:linear-gradient(145deg,#0d1b2d,#142842);border:1px solid rgba(96,165,250,.18);overflow:hidden}.flight-card>summary{list-style:none;cursor:pointer;padding:12px;display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center}.flight-card>summary::-webkit-details-marker{display:none}.flight-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,#2563eb,#7c3aed);font-size:20px}.flight-date{font-size:8px;font-weight:950;letter-spacing:.1em;color:#93c5fd}.flight-title{font-size:13px;font-weight:950;color:#fff;margin-top:3px}.flight-route{font-size:9px;color:#a9bdd2;margin-top:2px}.flight-expand{font-size:17px;color:#c4b5fd}.flight-card[open] .flight-expand{transform:rotate(45deg)}.flight-body{padding:0 12px 12px}.flight-status{display:inline-flex;padding:4px 7px;border-radius:999px;background:rgba(16,185,129,.11);border:1px solid rgba(52,211,153,.2);font-size:7px;font-weight:950;letter-spacing:.07em;color:#6ee7b7;margin-bottom:9px}.flight-status.pending{background:rgba(245,158,11,.09);border-color:rgba(245,158,11,.2);color:#fbbf24}.flight-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.flight-fact{padding:9px;border-radius:12px;background:#ffffff07;border:1px solid #ffffff0d}.flight-fact b{display:block;font-size:7px;letter-spacing:.07em;color:#93c5fd;margin-bottom:3px;text-transform:uppercase}.flight-fact span{display:block;font-size:9px;line-height:1.4;color:#d5e0ed}.flight-transfer{margin-top:8px;padding:9px;border-radius:12px;background:rgba(37,99,235,.08);border:1px solid rgba(96,165,250,.15);font-size:9px;line-height:1.45;color:#bfdbfe}.flight-notes{margin:8px 0 0;padding-left:16px;color:#aebdd0;font-size:9px;line-height:1.5}
.hotel-list,.coverage-grid{display:grid;gap:8px;padding-top:10px}.hotel-stay{padding:11px;border-radius:14px;background:#ffffff07;border:1px solid #ffffff0d}.hotel-stay-head{display:flex;justify-content:space-between;gap:8px}.hotel-stay b{font-size:11px;color:#fff}.hotel-stay em{font-style:normal;color:#fbbf24;font-size:8px;font-weight:900}.hotel-city{font-size:8px;color:#93c5fd;font-weight:900;letter-spacing:.08em;text-transform:uppercase}.hotel-address{font-size:8px;line-height:1.45;color:#94a3b8;margin-top:4px}.hotel-map{display:inline-flex;margin-top:7px;text-decoration:none;color:#bfdbfe;font-size:8px;font-weight:900}.coverage-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.coverage-box{padding:11px;border-radius:14px;background:#ffffff07;border:1px solid #ffffff0d}.coverage-box b{font-size:10px;color:#fff}.coverage-box ul{padding-left:15px;margin:7px 0 0;color:#aebed0;font-size:8px;line-height:1.5}@media(max-width:520px){.coverage-grid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function flightCard(f,type){const pending=f.status.includes('PENDING');return `<details class="flight-card"><summary><div class="flight-icon">${type==='international'?'🌎':'✈️'}</div><div><div class="flight-date">${f.date}</div><div class="flight-title">${f.title}</div><div class="flight-route">${f.route}</div></div><div class="flight-expand">＋</div></summary><div class="flight-body"><span class="flight-status ${pending?'pending':''}">${f.status}</span><div class="flight-facts"><div class="flight-fact"><b>Airline</b><span>${f.airline}</span></div><div class="flight-fact"><b>Cabin / class</b><span>${f.class}</span></div><div class="flight-fact"><b>Departure</b><span>${f.depart}</span></div><div class="flight-fact"><b>Arrival</b><span>${f.arrive}</span></div>${f.baggage?`<div class="flight-fact"><b>Baggage</b><span>${f.baggage}</span></div>`:''}</div><div class="flight-transfer">🚘 <b>Ground transfer:</b> ${f.transfer}</div><ul class="flight-notes">${f.notes.map(n=>`<li>${n}</li>`).join('')}</ul></div></details>`}
function trainCard(t){const pending=t.status!=='CONFIRMED';return `<details class="flight-card"><summary><div class="flight-icon">🚄</div><div><div class="flight-date">${t.date}</div><div class="flight-title">${t.title}</div><div class="flight-route">${t.number} · ${t.time}</div></div><div class="flight-expand">＋</div></summary><div class="flight-body"><span class="flight-status ${pending?'pending':''}">${t.status}</span><div class="flight-facts"><div class="flight-fact"><b>Train</b><span>${t.number}</span></div><div class="flight-fact"><b>Time</b><span>${t.time}</span></div><div class="flight-fact"><b>Class</b><span>${t.class}</span></div><div class="flight-fact"><b>Ticket gate</b><span>${t.gate}</span></div><div class="flight-fact"><b>Carriage</b><span>${t.carriage}</span></div><div class="flight-fact"><b>Seats</b><span>${t.seats}</span></div></div><ul class="flight-notes">${t.notes.map(n=>`<li>${n}</li>`).join('')}</ul></div></details>`}
function group(label,icon,content,open=false){return `<details class="flight-group" ${open?'open':''}><summary>${icon} ${label}</summary><div class="detail-body">${content}</div></details>`}
function flightGroup(label,icon,data,type,open=false){return group(label,icon,`<div class="flight-detail-wrap">${data.map(f=>flightCard(f,type)).join('')}</div>`,open)}
function trainGroup(){return group('High-speed trains','🚄',`<div class="flight-detail-wrap">${trainData.map(trainCard).join('')}</div>`)}
function hotelGroup(){return group('Confirmed hotels · 13 nights','🏨',`<div class="hotel-list">${hotelData.map(h=>`<div class="hotel-stay"><div class="hotel-city">${h.city} · ${h.dates}</div><div class="hotel-stay-head"><b>${h.name}</b><em>${h.rating}</em></div><div class="hotel-address">${h.address}</div><a class="hotel-map" target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(h.map)}">📍 Open map</a></div>`).join('')}</div>`)}
function coverageGroup(){return group('What the land package covers','✅',`<div class="coverage-grid"><div class="coverage-box"><b>Included</b><ul>${coverage.included.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="coverage-box"><b>Not included</b><ul>${coverage.excluded.map(x=>`<li>${x}</li>`).join('')}</ul></div></div>`)}
function inject(){styles();const travel=document.querySelector('#travel')?.nextElementSibling;if(!travel||!travel.classList.contains('travel')||travel.dataset.tripUpgrade==='true')return;travel.dataset.tripUpgrade='true';[...travel.querySelectorAll(':scope>details')].forEach(d=>d.remove());travel.insertAdjacentHTML('afterbegin',flightGroup('International flights','🌎',flightData.international,'international',true)+flightGroup('Domestic flights','✈️',flightData.domestic,'domestic')+trainGroup()+hotelGroup()+coverageGroup())}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',inject);else inject();
})();
