(()=>{
const flightData={
 international:[
  {date:'AUG 30–31',title:'Tampa → Los Angeles → Shanghai',airline:'Delta',route:'TPA → LAX → PVG',depart:'Tampa · 7:00 AM · Aug 30',arrive:'Shanghai Pudong · 4:05 PM · Aug 31',class:'International itinerary',transfer:'Private airport pickup included on arrival in Shanghai',status:'CONFIRMED',notes:['Long-haul outbound journey to China','Arrival day is intentionally kept light after the private transfer to Pullman Shanghai Jing An']},
  {date:'SEP 13',title:'Shanghai → Detroit → Tampa',airline:'Delta',route:'PVG → DTW → TPA',depart:'Shanghai Pudong · 10:15 AM',arrive:'Tampa · 4:40 PM scheduled',class:'International itinerary',transfer:'Private airport drop-off included in Shanghai',status:'CONFIRMED',notes:['Final breakfast and hotel checkout before airport transfer','International return routing is Shanghai → Detroit → Tampa']}
 ],
 domestic:[
  {date:'SEP 2',title:'Shanghai → Zhangjiajie',airline:'Airline / flight number pending',route:'Shanghai → Zhangjiajie',depart:'Exact departure time pending',arrive:'Exact arrival time pending',class:'Economy Class',transfer:'Airport drop-off in Shanghai + private airport pickup in Zhangjiajie included',status:'TICKET DETAILS PENDING',notes:['After arrival: hotel check-in','Recommended free time: sunset viewpoint / 72 Strange Buildings']},
  {date:'SEP 12',title:'Beijing → Shanghai',airline:'Airline / flight number pending',route:'Beijing → Shanghai',depart:'After Great Wall + Temple of Heaven touring',arrive:'Exact arrival time pending',class:'Economy Class',transfer:'Airport drop-off in Beijing + private airport pickup in Shanghai included',status:'TICKET DETAILS PENDING',notes:['Touring happens first: Mutianyu Great Wall → Temple of Heaven','Final overnight: Pullman Shanghai Jing An']}
 ]
};
function styles(){if(document.getElementById('flightDetailStyles'))return;const s=document.createElement('style');s.id='flightDetailStyles';s.textContent=`
.flight-group>summary{display:flex!important;align-items:center;gap:9px}.flight-group>summary:after{content:'⌄';margin-left:auto;color:#93c5fd;font-size:16px}.flight-group[open]>summary:after{transform:rotate(180deg)}
.flight-detail-wrap{display:grid;gap:9px;padding:10px 0 3px}.flight-card{border-radius:17px;background:linear-gradient(145deg,#0d1b2d,#142842);border:1px solid rgba(96,165,250,.18);overflow:hidden}.flight-card>summary{list-style:none;cursor:pointer;padding:12px;display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center}.flight-card>summary::-webkit-details-marker{display:none}.flight-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,#2563eb,#7c3aed);font-size:20px}.flight-date{font-size:8px;font-weight:950;letter-spacing:.1em;color:#93c5fd}.flight-title{font-size:13px;font-weight:950;color:#fff;margin-top:3px}.flight-route{font-size:9px;color:#a9bdd2;margin-top:2px}.flight-expand{font-size:17px;color:#c4b5fd}.flight-card[open] .flight-expand{transform:rotate(45deg)}.flight-body{padding:0 12px 12px}.flight-status{display:inline-flex;padding:4px 7px;border-radius:999px;background:rgba(16,185,129,.11);border:1px solid rgba(52,211,153,.2);font-size:7px;font-weight:950;letter-spacing:.07em;color:#6ee7b7;margin-bottom:9px}.flight-status.pending{background:rgba(245,158,11,.09);border-color:rgba(245,158,11,.2);color:#fbbf24}.flight-facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px}.flight-fact{padding:9px;border-radius:12px;background:#ffffff07;border:1px solid #ffffff0d}.flight-fact b{display:block;font-size:7px;letter-spacing:.07em;color:#93c5fd;margin-bottom:3px;text-transform:uppercase}.flight-fact span{display:block;font-size:9px;line-height:1.4;color:#d5e0ed}.flight-transfer{margin-top:8px;padding:9px;border-radius:12px;background:rgba(37,99,235,.08);border:1px solid rgba(96,165,250,.15);font-size:9px;line-height:1.45;color:#bfdbfe}.flight-notes{margin:8px 0 0;padding-left:16px;color:#aebdd0;font-size:9px;line-height:1.5}.flight-pending-note{margin-top:10px;padding:9px 10px;border-radius:12px;background:rgba(245,158,11,.07);border:1px solid rgba(245,158,11,.16);font-size:8px;color:#d9c9a6;line-height:1.45}
`;
document.head.appendChild(s)}
function card(f,type){const pending=f.status.includes('PENDING');return `<details class="flight-card"><summary><div class="flight-icon">${type==='international'?'🌎':'✈️'}</div><div><div class="flight-date">${f.date}</div><div class="flight-title">${f.title}</div><div class="flight-route">${f.route}</div></div><div class="flight-expand">＋</div></summary><div class="flight-body"><span class="flight-status ${pending?'pending':''}">${f.status}</span><div class="flight-facts"><div class="flight-fact"><b>Airline</b><span>${f.airline}</span></div><div class="flight-fact"><b>Cabin / class</b><span>${f.class}</span></div><div class="flight-fact"><b>Departure</b><span>${f.depart}</span></div><div class="flight-fact"><b>Arrival</b><span>${f.arrive}</span></div></div><div class="flight-transfer">🚘 <b>Ground transfer:</b> ${f.transfer}</div><ul class="flight-notes">${f.notes.map(n=>`<li>${n}</li>`).join('')}</ul>${pending?'<div class="flight-pending-note">⏳ Exact airline, flight number, airport and departure/arrival times are not in the current tour documents. This card is ready to receive them as soon as the detailed itinerary is issued.</div>':''}</div></details>`}
function group(label,icon,data,type){return `<details class="flight-group" ${type==='international'?'open':''}><summary>${icon} ${label}</summary><div class="detail-body"><div class="flight-detail-wrap">${data.map(f=>card(f,type)).join('')}</div></div></details>`}
function inject(){styles();const travel=document.querySelector('#travel')?.nextElementSibling;if(!travel||!travel.classList.contains('travel')||travel.dataset.flightUpgrade==='true')return;travel.dataset.flightUpgrade='true';const details=[...travel.querySelectorAll(':scope>details')];details.filter(d=>/International flights/i.test(d.querySelector('summary')?.textContent||'')).forEach(d=>d.remove());const first=travel.firstElementChild;const wrap=document.createElement('div');wrap.innerHTML=group('International flights','🌎',flightData.international,'international')+group('Domestic flights','✈️',flightData.domestic,'domestic');const nodes=[...wrap.children];nodes.reverse().forEach(n=>travel.insertBefore(n,first));}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',inject);else inject();
})();