(()=>{
const VERCEL_API='https://china-2026-trip-one.vercel.app/api/weather';
const API_ENDPOINT=location.hostname.endsWith('.vercel.app')?'/api/weather':VERCEL_API;
const cityIds=['shanghai','zhangjiajie','furong','chengdu','xian','beijing'];
const cache=new Map();
let activeController=null,activeCity='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const conditions=code=>{
  if(code===0)return['☀️','Clear'];
  if(code<=2)return['🌤️',code===1?'Mostly clear':'Partly cloudy'];
  if(code===3)return['☁️','Overcast'];
  if(code===45||code===48)return['🌫️','Foggy'];
  if(code>=51&&code<=57)return['🌦️','Drizzle'];
  if(code>=61&&code<=67)return['🌧️','Rain'];
  if(code>=71&&code<=77)return['❄️','Snow'];
  if(code>=80&&code<=82)return['🌦️','Rain showers'];
  if(code>=85&&code<=86)return['🌨️','Snow showers'];
  if(code>=95)return['⛈️','Thunderstorms'];
  return['🌤️','Mixed conditions'];
};
const dayLabel=date=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${date}T12:00:00`));
function styles(){if(document.getElementById('weatherStyles'))return;const s=document.createElement('style');s.id='weatherStyles';s.textContent=`
.city-weather-btn{width:100%;margin:0 0 14px;padding:12px 14px;border:1px solid rgba(96,165,250,.24);border-radius:16px;background:linear-gradient(135deg,rgba(37,99,235,.18),rgba(14,165,233,.1));color:#e0f2fe;display:flex;align-items:center;gap:10px;text-align:left;cursor:pointer;touch-action:manipulation}.city-weather-icon{width:39px;height:39px;flex:0 0 39px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,#2563eb,#06b6d4);font-size:20px}.city-weather-btn b{display:block;font-size:12px}.city-weather-btn small{display:block;color:#91aeca;font-size:9px;margin-top:2px}.city-weather-arrow{margin-left:auto;font-size:20px;color:#7dd3fc}
.weather-modal{position:fixed;inset:0;z-index:155;background:rgba(3,8,18,.8);backdrop-filter:blur(16px);display:none;align-items:flex-end;padding-top:calc(env(safe-area-inset-top,0px) + 44px)}.weather-modal.show{display:flex}.weather-sheet{width:100%;max-height:calc(100dvh - env(safe-area-inset-top,0px) - 52px);overflow:auto;overscroll-behavior:contain;-webkit-overflow-scrolling:touch;border-radius:28px 28px 0 0;padding:0 14px calc(34px + env(safe-area-inset-bottom,0px));background:radial-gradient(circle at 80% 0,rgba(14,165,233,.22),transparent 31%),linear-gradient(180deg,#111d30,#08111f);border-top:1px solid rgba(255,255,255,.15);box-shadow:0 -25px 80px rgba(0,0,0,.48)}.weather-top{position:sticky;top:0;z-index:4;padding:12px 0 10px;background:linear-gradient(180deg,#111d30 76%,rgba(17,29,48,.95))}.weather-handle{width:42px;height:4px;border-radius:8px;background:#ffffff30;margin:0 auto 12px}.weather-head{display:flex;gap:12px;align-items:flex-start}.weather-kicker{font-size:8px;font-weight:950;letter-spacing:.15em;color:#7dd3fc}.weather-head h2{font-size:27px;line-height:1;margin:4px 0}.weather-status{font-size:9px;color:#9fb1c8;margin-top:6px}.weather-close{margin-left:auto;width:46px;height:46px;flex:0 0 46px;border-radius:50%;border:1px solid #ffffff30;background:#ffffff12;color:#fff;font-size:25px;display:grid;place-items:center;cursor:pointer}.weather-list{display:grid;gap:9px;padding-top:4px}.weather-day{display:grid;grid-template-columns:58px 1fr auto;gap:10px;align-items:center;padding:12px;border-radius:17px;background:linear-gradient(145deg,#0e1b2e,#142640);border:1px solid rgba(255,255,255,.08)}.weather-emoji{width:58px;height:58px;border-radius:16px;display:grid;place-items:center;background:linear-gradient(135deg,#2563eb,#0891b2);font-size:29px}.weather-date{font-size:9px;font-weight:950;letter-spacing:.06em;color:#93c5fd;text-transform:uppercase}.weather-condition{font-size:12px;font-weight:900;color:#fff;margin-top:3px}.weather-extra{font-size:9px;color:#9fb1c8;margin-top:5px}.weather-temp{text-align:right}.weather-high{font-size:20px;font-weight:950;color:#fff}.weather-low{font-size:11px;color:#93a6bd;margin-top:2px}.weather-loading{width:28px;height:28px;border:3px solid #ffffff20;border-top-color:#38bdf8;border-radius:50%;animation:weatherSpin .8s linear infinite;margin:38px auto}.weather-error{padding:14px;border-radius:16px;background:#ffffff07;border:1px solid #ffffff10;color:#cbd5e1;font-size:11px;line-height:1.5}.weather-retry{margin-top:10px;border:0;border-radius:999px;padding:9px 12px;background:linear-gradient(135deg,#2563eb,#0891b2);color:#fff;font-weight:900}.weather-source{text-align:center;color:#71849a;font-size:8px;padding:13px 0 2px}.weather-source a{color:#7dd3fc}@keyframes weatherSpin{to{transform:rotate(360deg)}}
`;document.head.appendChild(s)}
function render(data){const list=document.getElementById('weatherList');document.getElementById('weatherStatus').textContent=`7-day outlook · ${data.timezone?.replace('_',' ')||'local time'}`;list.innerHTML=data.forecast.map((d,i)=>{const [icon,label]=conditions(Number(d.code));return `<article class="weather-day"><div class="weather-emoji">${icon}</div><div><div class="weather-date">${i===0?'Today · ':''}${dayLabel(d.date)}</div><div class="weather-condition">${label}</div><div class="weather-extra">💧 ${Math.round(Number(d.rainChance)||0)}% rain · 💨 ${Math.round(Number(d.wind)||0)} mph</div></div><div class="weather-temp"><div class="weather-high">${Math.round(Number(d.high))}°</div><div class="weather-low">${Math.round(Number(d.low))}° low</div></div></article>`}).join('')+'<div class="weather-source">Forecast data by <a href="https://open-meteo.com/" target="_blank" rel="noopener">Open-Meteo</a></div>'}
async function load(city,force=false){activeCity=city;const list=document.getElementById('weatherList'),cached=cache.get(city);if(!force&&cached&&Date.now()-cached.at<1800000){render(cached.data);return}activeController?.abort();activeController=new AbortController();document.getElementById('weatherStatus').textContent='Loading the latest forecast…';list.innerHTML='<div class="weather-loading" aria-label="Loading forecast"></div>';try{const response=await fetch(`${API_ENDPOINT}?city=${encodeURIComponent(city)}`,{headers:{Accept:'application/json'},signal:activeController.signal});if(!response.ok)throw new Error(`Weather service returned ${response.status}`);const data=await response.json();cache.set(city,{at:Date.now(),data});render(data)}catch(error){if(error.name==='AbortError')return;document.getElementById('weatherStatus').textContent='Forecast temporarily unavailable';list.innerHTML='<div class="weather-error">The live weather service could not be reached. Please try again in a moment.<br><button class="weather-retry" type="button">Try again</button></div>';list.querySelector('.weather-retry')?.addEventListener('click',()=>load(activeCity,true))}}
function init(){if(document.getElementById('weatherModal'))return;styles();const modal=document.createElement('div');modal.className='weather-modal';modal.id='weatherModal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<section class="weather-sheet" role="dialog" aria-modal="true" aria-labelledby="weatherTitle"><div class="weather-top"><div class="weather-handle"></div><div class="weather-head"><div><div class="weather-kicker">LIVE CITY WEATHER</div><h2 id="weatherTitle">7-Day Forecast</h2><div class="weather-status" id="weatherStatus">Loading the latest forecast…</div></div><button class="weather-close" type="button" aria-label="Close weather forecast">×</button></div></div><div class="weather-list" id="weatherList"></div></section>';document.body.appendChild(modal);const open=city=>{const card=document.getElementById(city),name=card?.querySelector('.city-copy b')?.textContent||city;document.getElementById('weatherTitle').textContent=name;modal.classList.add('show');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';modal.querySelector('.weather-sheet').scrollTop=0;load(city)},close=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';activeController?.abort()};cityIds.forEach(city=>{const body=document.getElementById(city)?.querySelector('.city-body');if(!body||body.querySelector('.city-weather-btn'))return;const button=document.createElement('button');button.type='button';button.className='city-weather-btn';button.innerHTML='<span class="city-weather-icon">🌤️</span><span><b>7-Day Weather</b><small>Live forecast for this city</small></span><span class="city-weather-arrow">›</span>';button.addEventListener('click',()=>open(city));body.insertAdjacentElement('afterbegin',button)});modal.querySelector('.weather-close').addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))close()})}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();
