(()=>{
const API=location.hostname.endsWith('.vercel.app')?'/api/spas':'https://china-2026-trip-one.vercel.app/api/spas';
const miles=m=>m==null?'Nearby':m<160?`${Math.round(m)} m`:`${(m/1609.344).toFixed(1)} mi`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function styles(){if(document.getElementById('spaStyles'))return;const s=document.createElement('style');s.id='spaStyles';s.textContent=`
.spa-tool{margin:18px 14px;padding:16px;border-radius:22px;background:radial-gradient(circle at 85% 0,rgba(20,184,166,.2),transparent 35%),linear-gradient(145deg,#10202c,#101827);border:1px solid rgba(45,212,191,.2);box-shadow:0 16px 40px rgba(0,0,0,.18)}.spa-head{display:flex;gap:11px;align-items:center}.spa-icon{width:44px;height:44px;border-radius:14px;display:grid;place-items:center;font-size:22px;background:linear-gradient(135deg,#14b8a6,#0ea5e9)}.spa-head h3{font-size:15px;margin:0;color:#fff}.spa-head p{font-size:9px;color:#9fb3c8;margin:3px 0 0}.spa-find{margin-left:auto;border:0;border-radius:999px;padding:9px 12px;background:linear-gradient(135deg,#14b8a6,#0ea5e9);color:#fff;font:900 9px system-ui}.spa-status{font-size:9px;color:#94a3b8;margin:11px 0 0}.spa-list{display:grid;gap:8px;margin-top:10px}.spa-card{padding:11px;border-radius:15px;background:#ffffff07;border:1px solid #ffffff0e}.spa-top{display:flex;justify-content:space-between;gap:8px}.spa-name{font-size:12px;font-weight:950;color:#fff}.spa-distance{font-size:9px;font-weight:900;color:#67e8f9;white-space:nowrap}.spa-meta{font-size:9px;color:#aebed0;margin-top:4px;line-height:1.4}.spa-hours{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:7px}.spa-open,.spa-closed,.spa-24{padding:4px 7px;border-radius:999px;font-size:7px;font-weight:950;letter-spacing:.05em}.spa-open{background:rgba(34,197,94,.12);color:#86efac}.spa-closed{background:rgba(239,68,68,.11);color:#fca5a5}.spa-24{background:linear-gradient(135deg,rgba(168,85,247,.2),rgba(59,130,246,.2));border:1px solid rgba(192,132,252,.25);color:#ddd6fe}.spa-map{display:inline-flex;margin-top:8px;text-decoration:none;padding:6px 9px;border-radius:999px;background:#ffffff0a;border:1px solid #ffffff12;color:#bae6fd;font-size:8px;font-weight:900}.spa-empty{padding:12px;border-radius:14px;background:#ffffff06;color:#b9c7d7;font-size:9px;line-height:1.45}
`;document.head.appendChild(s)}
function render(root,spas){const list=root.querySelector('.spa-list');list.innerHTML=spas.length?spas.map(x=>`<div class="spa-card"><div class="spa-top"><div class="spa-name">${esc(x.name)}</div><div class="spa-distance">${miles(x.distanceMeters)}</div></div><div class="spa-meta">⭐ ${x.rating?Number(x.rating).toFixed(1):'—'}${x.reviews?` · ${Number(x.reviews).toLocaleString()} reviews`:''}${x.address?`<br>${esc(x.address)}`:''}</div><div class="spa-hours">${x.is24Hours?'<span class="spa-24">🌙 OPEN 24 HOURS</span>':x.openNow===true?'<span class="spa-open">OPEN NOW</span>':x.openNow===false?'<span class="spa-closed">CLOSED NOW</span>':''}<span class="spa-meta">Today: ${esc(x.todayHours)}</span></div><a class="spa-map" target="_blank" rel="noopener" href="${esc(x.maps)}">📍 Open in Maps</a></div>`).join(''):'<div class="spa-empty">No spas were returned within about 5 miles. Try again from another location.</div>'}
function lookup(root){const status=root.querySelector('.spa-status'),list=root.querySelector('.spa-list');if(!navigator.geolocation){status.textContent='Location is not supported by this browser.';return}status.textContent='Finding your location…';list.innerHTML='';navigator.geolocation.getCurrentPosition(async p=>{status.textContent=`Location found · searching nearby spas…`;try{const r=await fetch(`${API}?lat=${encodeURIComponent(p.coords.latitude)}&lng=${encodeURIComponent(p.coords.longitude)}`);if(!r.ok)throw new Error();const data=await r.json();status.textContent=`${data.spas.length} closest spas · sorted by distance from your phone`;render(root,data.spas)}catch{status.textContent='Spa search is temporarily unavailable.';list.innerHTML='<div class="spa-empty">We could not load live spa results. Please try again.</div>'}},()=>{status.textContent='Location permission is needed to find spas near you.'},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})}
function init(){if(document.getElementById('nearbySpaTool'))return;styles();const section=document.createElement('section');section.id='nearbySpaTool';section.className='spa-tool';section.innerHTML='<div class="spa-head"><div class="spa-icon">♨️</div><div><h3>Nearby Spas</h3><p>Closest relaxation, massage & wellness options</p></div><button class="spa-find" type="button">USE MY LOCATION</button></div><div class="spa-status">Tap to find the closest spas using your phone’s GPS.</div><div class="spa-list"></div>';const travel=document.querySelector('#travel')?.nextElementSibling;const anchor=travel||document.querySelector('main')||document.body;if(travel)travel.insertAdjacentElement('afterend',section);else anchor.appendChild(section);section.querySelector('.spa-find').addEventListener('click',()=>lookup(section))}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init);else init();
})();