(()=>{
const tailors=[
 {name:'Saint Angelo Bespoke',branch:'Shanghai Jing’an Store',address:'Room 901A, 9F, Global World Building, No. 172 Yuyuan Road, Jing’an District, Shanghai',query:'Saint Angelo Bespoke 172 Yuyuan Road Shanghai'},
 {name:'Glamour Sartorial Bespoke Tailoring',branch:'Shanghai',address:'No. 1419 South Suzhou Road, Shanghai',query:'Glamour Sartorial Bespoke Tailoring 1419 South Suzhou Road Shanghai'},
 {name:'Lord of Suits Bespoke Tailoring',branch:'Putuo Store',address:'No. 1005 Xikang Road, Putuo District, Shanghai · Near Changshou Road Station, Metro Lines 7 & 13, OCT Commercial Area',query:'Lord of Suits Bespoke Tailoring 1005 Xikang Road Shanghai'}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function styles(){if(document.getElementById('suitStyles'))return;const s=document.createElement('style');s.id='suitStyles';s.textContent=`
.suit-section{margin:14px 0}.suit-section>summary{list-style:none;cursor:pointer;display:flex;align-items:center;gap:10px;padding:13px;border-radius:17px;background:radial-gradient(circle at 90% 0,rgba(217,119,6,.18),transparent 38%),linear-gradient(145deg,#172033,#111827);border:1px solid rgba(251,191,36,.2)}.suit-section>summary::-webkit-details-marker{display:none}.suit-icon{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;font-size:21px;background:linear-gradient(135deg,#b45309,#d97706)}.suit-head{flex:1}.suit-kicker{font-size:7px;letter-spacing:.12em;font-weight:950;color:#fbbf24}.suit-title{font-size:14px;font-weight:950;color:#fff;margin-top:3px}.suit-sub{font-size:9px;color:#aebed0;margin-top:2px}.suit-chevron{font-size:17px;color:#fcd34d}.suit-section[open] .suit-chevron{transform:rotate(180deg)}.suit-body{padding:9px 1px 2px;display:grid;gap:8px}.tailor-card{padding:11px;border-radius:15px;background:linear-gradient(145deg,#0f1b2c,#15243a);border:1px solid rgba(255,255,255,.09)}.tailor-num{display:inline-grid;place-items:center;width:25px;height:25px;border-radius:9px;background:linear-gradient(135deg,#b45309,#d97706);font-size:9px;font-weight:950;margin-right:7px}.tailor-name{font-size:12px;font-weight:950;color:#fff}.tailor-branch{font-size:8px;color:#fbbf24;margin:4px 0}.tailor-address{font-size:9px;line-height:1.45;color:#aebed0;margin:6px 0 8px}.tailor-actions{display:flex;gap:6px;flex-wrap:wrap}.tailor-actions a{display:inline-flex;text-decoration:none;padding:6px 9px;border-radius:999px;background:#ffffff09;border:1px solid #ffffff13;color:#dbeafe;font-size:8px;font-weight:900}.suit-note{padding:10px;border-radius:13px;background:rgba(245,158,11,.07);border:1px solid rgba(245,158,11,.15);font-size:8px;line-height:1.45;color:#d9c9a6}
`;document.head.appendChild(s)}
function markup(){return `<details class="suit-section"><summary><div class="suit-icon">🤵</div><div class="suit-head"><div class="suit-kicker">SHANGHAI · PERSONAL ERRAND</div><div class="suit-title">Custom Suit · Bespoke Tailors</div><div class="suit-sub">Tour-company recommendations · tap to expand</div></div><div class="suit-chevron">⌄</div></summary><div class="suit-body">${tailors.map((t,i)=>`<div class="tailor-card"><div><span class="tailor-num">${i+1}</span><span class="tailor-name">${esc(t.name)}</span></div><div class="tailor-branch">${esc(t.branch)}</div><div class="tailor-address">📍 ${esc(t.address)}</div><div class="tailor-actions"><a target="_blank" rel="noopener" href="https://maps.apple.com/?q=${encodeURIComponent(t.query)}">🍎 Apple Maps</a><a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(t.query)}">🗺️ Google Maps</a><a target="_blank" rel="noopener" href="https://www.google.com/search?q=${encodeURIComponent(t.name+' Shanghai tailor')}">🔎 Search</a></div></div>`).join('')}<div class="suit-note">💡 <b>Tailoring plan:</b> schedule the first fitting as early in the Shanghai stay as practical. Bespoke work often benefits from at least one follow-up fitting before final pickup. These three shops were recommended by the tour company; confirm current hours and appointment availability before visiting.</div></div></details>`}
function inject(){styles();const city=document.getElementById('shanghai');if(!city||city.querySelector('.suit-section'))return;const body=city.querySelector('.city-body');if(!body)return;const dayHeading=[...body.querySelectorAll('h3')].find(h=>/Day plans/i.test(h.textContent));if(dayHeading)dayHeading.insertAdjacentHTML('beforebegin',markup());else body.insertAdjacentHTML('beforeend',markup())}
if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',inject);else inject();
})();