import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const config=JSON.parse(fs.readFileSync(path.join(root,'site.config.json'),'utf8'));
const check=process.argv.includes('--check');
if(!/^\d{8}-\d+$/.test(config.version))throw new Error('site.config.json needs a YYYYMMDD-N version');
if(!Array.isArray(config.tripModules)||!config.tripModules.length)throw new Error('tripModules must not be empty');
const modules=config.tripModules.map(file=>{
  if(!/^data\/[a-z0-9-]+\.js$/.test(file)||file==='data/trips.js')throw new Error(`Invalid trip module: ${file}`);
  return `// Source: ${file}\n${fs.readFileSync(path.join(root,file),'utf8').trimEnd()}`;
});
const bundle=`// Generated by scripts/prepare-release.mjs. Edit source modules, not this file.\n${modules.join('\n\n')}\n`;
const versionPattern=/\?v=\d{8}-\d+/g;
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const worker=fs.readFileSync(path.join(root,'sw.js'),'utf8');
if(!html.includes('src="/data/trips.js?')||!worker.includes("'/data/trips.js'"))throw new Error('Trip bundle is missing from the page or offline cache');
if(!/\?v=\d{8}-\d+/.test(html)||!/const BUILD='\d{8}-\d+';/.test(app)||!/const VERSION='\d{8}-\d+';/.test(worker))throw new Error('Release version markers are missing');
const updates=new Map([
  ['data/trips.js',bundle],
  ['index.html',html.replace(versionPattern,`?v=${config.version}`)],
  ['app.js',app.replace(/const BUILD='\d{8}-\d+';/,`const BUILD='${config.version}';`)],
  ['sw.js',worker.replace(/const VERSION='\d{8}-\d+';/,`const VERSION='${config.version}';`)]
]);
let stale=false;
for(const [file,expected] of updates){
  const target=path.join(root,file);
  const current=fs.existsSync(target)?fs.readFileSync(target,'utf8'):'';
  if(current===expected)continue;
  stale=true;
  if(!check)fs.writeFileSync(target,expected);
  console.log(`${check?'STALE':'UPDATED'} ${file}`);
}
if(check&&stale)process.exitCode=1;
else console.log(`OK: ${config.appName} release ${config.version}${check?' is current':''}`);
